### ISSUE TITLE
Source code AI

### ISSUE THREAD

**Issue by longtran84** [hutch120/OpenALPRBrowserDemo#2]
do you have open source code AI ?

**Comment by hutch120** [comment]
Huh? Not sure what you mean. This code is public.

**Comment by longtran84** [comment]
@hutch120 i mean, do you have source code Backend to build Automatic License Plate Recognition  ?

**Comment by hutch120** [comment]
The backend is a managed service provided by OpenALPR. I'm pretty sure they have a wrapper around something... not sure what. I did this as a customer demo. Never turned into a project.
